<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $services = [
            "BCH" => "Hospital Services",
            "GO-BLOM" => "BLOM Services",
            "GO-MSSD" => "Executive Services",
            "GO-EESD" => "Education Services",
            "GO-EESD" => "Employment Services",
            "GO-EESD" => "Review Assistance",
            "GO-EESD" => "Scholarship",
            "ENRO" => "Consultation",
            "ENRO" => "EMSD",
            "ENRO" => "FWRMS",
            "ENRO" => "Mineral Resources",
            "GO" => "Assistance",
            "GO" => "COS Consulting Clients",
            "GO" => "Walk-in Clients",
            "GO-GSMAC" => "Referral",
            "GO-GSMAC" => "Walk-in",
            "GO-IASD" => "Internal Audit Services ",
            "GO-LSI" => "LSI Services",
            "NCH" => "Hospital Services",
            "GO-OMBC" => "OMBC Services",
            "OMCDH" => "Hospital Services",
            "OMPH" => "Administrative Services",
            "OMPH" => "Assistance/Information",
            "OMPH" => "Billing",
            "OMPH" => "Delivery Room",
            "OMPH" => "Dental",
            "OMPH" => "Dietary",
            "OMPH" => "ER",
            "OMPH" => "Family Planning",
            "OMPH" => "Housekeeping",
            "OMPH" => "ICU",
            "OMPH" => "Laboratory",
            "OMPH" => "Medical Ward",
            "OMPH" => "MIS",
            "OMPH" => "Nursing Services",
            "OMPH" => "OB Ward",
            "OMPH" => "OPD",
            "OMPH" => "Orthopedic",
            "OMPH" => "Payward",
            "OMPH" => "Pedia",
            "OMPH" => "Pharmacy",
            "OMPH" => "PhilHealth",
            "OMPH" => "Pulmonary",
            "OMPH" => "Radiology",
            "OMPH" => "Records",
            "OMPH" => "Security Services",
            "OMPH" => "Social Services",
            "OMPH" => "Surgery",
            "OMPH" => "X-ray",
            "OMSDH" => "Ambulance",
            "OMSDH" => "Animal Bite Treatment Center Services",
            "OMSDH" => "Billing",
            "OMSDH" => "C S S R Services",
            "OMSDH" => "Cashier Services",
            "OMSDH" => "Charity Services",
            "OMSDH" => "Delivery Room Services",
            "OMSDH" => "Dental Services",
            "OMSDH" => "Dietary Services",
            "OMSDH" => "Emergency Room Services",
            "OMSDH" => "Family Planning Services",
            "OMSDH" => "Laboratory Services",
            "OMSDH" => "OPD Services",
            "OMSDH" => "Payward Services",
            "OMSDH" => "Pharmacy Services",
            "OMSDH" => "PhilHealth Services",
            "OMSDH" => "Pre-Natal",
            "OMSDH" => "Records Services",
            "OMSDH" => "Social Services",
            "OMSDH" => "TB Dots Services",
            "OMSDH" => "Utility Services",
            "OMSDH" => "X-ray",
            "OPA" => "Accounting Services",
            "PA" => "Administrative Services",
            "PA" => "Facility Use Request",
            "PA" => "ODPMD Review of Design",
            "PA" => "ODPMD-ISO",
            "PA" => "ODPMD-Validation",
            "PA-ARTA" => "ARTA Desk",
            "PAgO" => "Administrative Services",
            "PAgO" => "Agro Services",
            "PAgO" => "Fisheries",
            "PAgO" => "Food Corridor",
            "PAgO" => "Technical Services",
            "PAsO" => "Records",
            "PAsO" => "Research",
            "PAsO" => "Transfer",
            "PBO" => "Technical Assistance",
            "GO-PDCMD" => "Administrative Services",
            "GO-PDCMD" => "Inmates Visitation",
            "GO-PDCMD-Pinamalayan" => "Jail Management Services",
            "GO-PDCMD-Roxas" => "Jail Management Services",
            "PDRRMO" => "DRRM Services",
            "PEO" => "Engineering Services",
            "PEO" => "Post- inspection Issuance Services",
            "PEO" => "Pre- inspection Issuance Services",
            "PGSO" => "Administrative Services",
            "PGSO" => "Records and Archives Management Services",
            "PGSO" => "Supply and Property Management Services",
            "PHO" => "Technical Services",
            "PHO" => "Dental - Extraction",
            "PHO" => "Dental - Filling ",
            "PHO" => "Dental - Oral Prophylaxis",
            "PHRMO" => "ADMINISTRITATIVE SERVICES",
            "PHRMO" => "COMPETENCY ENHANCEMENT",
            "PHRMO" => "HRDC",
            "PHRMO" => "MASTERAL",
            "PHRMO" => "ORIENTATION OF NEW ENTRANTS",
            "PHRMO" => "PUBLIC ASSISTANCE ",
            "PHRMO" => "RECRUITMENT, SELECTION AND PLACEMENT   (NP)",
            "PHRMO" => "RECRUITMENT, SELECTION AND PLACEMENT (P)",
            "PHRMO" => "WELFARE PROGRAMS",
            "PA-MISD" => "LAN & Internet Connection",
            "PA-MISD" => "LED WALL OPERATION",
            "PA-MISD" => "Media Scanning",
            "PA-MISD" => "Post Inspection",
            "PA-MISD" => "Pre-Purchase",
            "PA-MISD" => "Preventive Maintenance",
            "PA-MISD" => "Request for Service",
            "GO-PISD" => "Administrative Services",
            "GO-PISD" => "Information Management Services",
            "PLO" => "Legal Advise",
            "PLO" => "Legal Review",
            "PPDO" => "CLUP",
            "PPDO" => "Planning Services",
            "PPDO" => "Provision of Data/ Information/Maps to Clients",
            "PPDO" => "Provision of Technical Services (CSO)",
            "PPDO" => "Review of Program/ Project Design",
            "PPDO" => "Review of Program/ Training/Activity/Project Design",
            "ProVet" => "Administrative Services",
            "ProVet" => "Animal Health Services",
            "ProVet" => "Animal Production Services",
            "PSWDO" => "PSWDO Services",
            "PTIEDO" => "PTIEDO Services",
            "PTIEDO-Tourism" => "Tourism Services",
            "PTO" => "Admin Services",
            "PTO" => "Cash Disbursement Services",
            "PTO" => "Cert. of Credible Tax",
            "PTO" => "Cert. of Sand and Gravel",
            "PTO" => "Cert. of Transport",
            "PTO" => "Real Property Tax Services",
            "GO-SCD" => "Special Concerns' Services",
            "SP-OVG" => "Assisting Clients",
            "SP-Records" => "Local Legislation/ SP Records"
        ];

        foreach ($services as $office => $service) {
            $officeMatch = \App\Models\Office::where('abbr', $office)->first();
            if ($officeMatch) {
                //create service
                \App\Models\Service::create([
                    'office_id' => $officeMatch->id,
                    'name' => $service
                ]);
            } else {
                dd($office, $service);
            }
        }

    }
}
