<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $services = [
            ["office" => "BCH", "service" => "Hospital Services"],
            ["office" => "BCH", "service" => "Other Services"],
            ["office" => "GO-BLOM", "service" => "BLOM Services"],
            ["office" => "GO-BLOM", "service" => "Other Services"],
            ["office" => "GO-MSSD", "service" => "Executive Services"],
            ["office" => "GO-MSSD", "service" => "Other Services"],
            ["office" => "GO-EESD", "service" => "Education Services"],
            ["office" => "GO-EESD", "service" => "Employment Services"],
            ["office" => "GO-EESD", "service" => "Review Assistance"],
            ["office" => "GO-EESD", "service" => "Scholarship"],
            ["office" => "GO-EESD", "service" => "Other Services"],
            ["office" => "ENRO", "service" => "Consultation"],
            ["office" => "ENRO", "service" => "EMSD"],
            ["office" => "ENRO", "service" => "FWRMS"],
            ["office" => "ENRO", "service" => "Mineral Resources"],
            ["office" => "ENRO", "service" => "Other Services"],
            ["office" => "GO", "service" => "Assistance"],
            ["office" => "GO", "service" => "COS Consulting Clients"],
            ["office" => "GO", "service" => "Walk-in Clients"],
            ["office" => "GO", "service" => "Other Services"],
            ["office" => "GO-GSMAC", "service" => "Referral"],
            ["office" => "GO-GSMAC", "service" => "Walk-in"],
            ["office" => "GO-GSMAC", "service" => "Other Services"],
            ["office" => "GO-IASD", "service" => "Internal Audit Services"],
            ["office" => "GO-IASD", "service" => "Other Services"],
            ["office" => "GO-LSI", "service" => "LSI Services"],
            ["office" => "GO-LSI", "service" => "Other Services"],
            ["office" => "NCH", "service" => "Hospital Services"],
            ["office" => "NCH", "service" => "Other Services"],
            ["office" => "GO-OMBC", "service" => "OMBC Services"],
            ["office" => "GO-OMBC", "service" => "Other Services"],
            ["office" => "OMCDH", "service" => "Hospital Services"],
            ["office" => "OMCDH", "service" => "Other Services"],
            ["office" => "OMPH", "service" => "Administrative Services"],
            ["office" => "OMPH", "service" => "Assistance/Information"],
            ["office" => "OMPH", "service" => "Billing"],
            ["office" => "OMPH", "service" => "Delivery Room"],
            ["office" => "OMPH", "service" => "Dental"],
            ["office" => "OMPH", "service" => "Dietary"],
            ["office" => "OMPH", "service" => "ER"],
            ["office" => "OMPH", "service" => "Family Planning"],
            ["office" => "OMPH", "service" => "Housekeeping"],
            ["office" => "OMPH", "service" => "ICU"],
            ["office" => "OMPH", "service" => "Laboratory"],
            ["office" => "OMPH", "service" => "Medical Ward"],
            ["office" => "OMPH", "service" => "MIS"],
            ["office" => "OMPH", "service" => "Nursing Services"],
            ["office" => "OMPH", "service" => "OB Ward"],
            ["office" => "OMPH", "service" => "OPD"],
            ["office" => "OMPH", "service" => "Orthopedic"],
            ["office" => "OMPH", "service" => "Payward"],
            ["office" => "OMPH", "service" => "Pedia"],
            ["office" => "OMPH", "service" => "Pharmacy"],
            ["office" => "OMPH", "service" => "PhilHealth"],
            ["office" => "OMPH", "service" => "Pulmonary"],
            ["office" => "OMPH", "service" => "Radiology"],
            ["office" => "OMPH", "service" => "Records"],
            ["office" => "OMPH", "service" => "Security Services"],
            ["office" => "OMPH", "service" => "Social Services"],
            ["office" => "OMPH", "service" => "Surgery"],
            ["office" => "OMPH", "service" => "X-ray"],
            ["office" => "OMPH", "service" => "Other Services"],
            ["office" => "OMSDH", "service" => "Ambulance"],
            ["office" => "OMSDH", "service" => "Animal Bite Treatment Center Services"],
            ["office" => "OMSDH", "service" => "Billing"],
            ["office" => "OMSDH", "service" => "C S S R Services"],
            ["office" => "OMSDH", "service" => "Cashier Services"],
            ["office" => "OMSDH", "service" => "Charity Services"],
            ["office" => "OMSDH", "service" => "Delivery Room Services"],
            ["office" => "OMSDH", "service" => "Dental Services"],
            ["office" => "OMSDH", "service" => "Dietary Services"],
            ["office" => "OMSDH", "service" => "Emergency Room Services"],
            ["office" => "OMSDH", "service" => "Family Planning Services"],
            ["office" => "OMSDH", "service" => "Laboratory Services"],
            ["office" => "OMSDH", "service" => "OPD Services"],
            ["office" => "OMSDH", "service" => "Payward Services"],
            ["office" => "OMSDH", "service" => "Pharmacy Services"],
            ["office" => "OMSDH", "service" => "PhilHealth Services"],
            ["office" => "OMSDH", "service" => "Pre-Natal"],
            ["office" => "OMSDH", "service" => "Records Services"],
            ["office" => "OMSDH", "service" => "Social Services"],
            ["office" => "OMSDH", "service" => "TB Dots Services"],
            ["office" => "OMSDH", "service" => "Utility Services"],
            ["office" => "OMSDH", "service" => "X-ray"],
            ["office" => "OMSDH", "service" => "Other Services"],
            ["office" => "OPA", "service" => "Accounting Services"],
            ["office" => "OPA", "service" => "Other Services"],
            ["office" => "PA", "service" => "Administrative Services"],
            ["office" => "PA", "service" => "Facility Use Request"],
            ["office" => "PA", "service" => "ODPMD Review of Design"],
            ["office" => "PA", "service" => "ODPMD-ISO"],
            ["office" => "PA", "service" => "ODPMD-Validation"],
            ["office" => "PA", "service" => "Other Services"],
            ["office" => "PA-ARTA", "service" => "ARTA Desk"],
            ["office" => "PA-ARTA", "service" => "Other Services"],
            ["office" => "PAgO", "service" => "Administrative Services"],
            ["office" => "PAgO", "service" => "Agro Services"],
            ["office" => "PAgO", "service" => "Fisheries"],
            ["office" => "PAgO", "service" => "Food Corridor"],
            ["office" => "PAgO", "service" => "Technical Services"],
            ["office" => "PAgO", "service" => "Other Services"],
            ["office" => "PAsO", "service" => "Records"],
            ["office" => "PAsO", "service" => "Research"],
            ["office" => "PAsO", "service" => "Transfer"],
            ["office" => "PAsO", "service" => "Other Services"],
            ["office" => "PBO", "service" => "Technical Assistance"],
            ["office" => "PBO", "service" => "Other Services"],
            ["office" => "GO-PDCMD", "service" => "Administrative Services"],
            ["office" => "GO-PDCMD", "service" => "Inmates Visitation"],
            ["office" => "GO-PDCMD", "service" => "Other Services"],
            ["office" => "GO-PDCMD-Pinamalayan", "service" => "Jail Management Services"],
            ["office" => "GO-PDCMD-Pinamalayan", "service" => "Other Services"],
            ["office" => "GO-PDCMD-Roxas", "service" => "Jail Management Services"],
            ["office" => "GO-PDCMD-Roxas", "service" => "Other Services"],
            ["office" => "PDRRMO", "service" => "DRRM Services"],
            ["office" => "PDRRMO", "service" => "Other Services"],
            ["office" => "PEO", "service" => "Engineering Services"],
            ["office" => "PEO", "service" => "Post- inspection Issuance Services"],
            ["office" => "PEO", "service" => "Pre- inspection Issuance Services"],
            ["office" => "PEO", "service" => "Other Services"],
            ["office" => "PGSO", "service" => "Administrative Services"],
            ["office" => "PGSO", "service" => "Records and Archives Management Services"],
            ["office" => "PGSO", "service" => "Supply and Property Management Services"],
            ["office" => "PGSO", "service" => "Other Services"],
            ["office" => "PHO", "service" => "Technical Services"],
            ["office" => "PHO", "service" => "Dental - Extraction"],
            ["office" => "PHO", "service" => "Dental - Filling "],
            ["office" => "PHO", "service" => "Dental - Oral Prophylaxis"],
            ["office" => "PHO", "service" => "Other Services"],
            ["office" => "PHRMO", "service" => "Administrative Services"],
            ["office" => "PHRMO", "service" => "Competency Enhancement"],
            ["office" => "PHRMO", "service" => "HRDC"],
            ["office" => "PHRMO", "service" => "Masteral"],
            ["office" => "PHRMO", "service" => "Orientation Of New Entrants"],
            ["office" => "PHRMO", "service" => "Public Assistance"],
            ["office" => "PHRMO", "service" => "Recruitment Selection And Placement (NP)"],
            ["office" => "PHRMO", "service" => "Recruitment Selection And Placement (P)"],
            ["office" => "PHRMO", "service" => "Welfare Programs"],
            ["office" => "PHRMO", "service" => "Other Services"],
            ["office" => "PA-MISD", "service" => "LAN & Internet Connection"],
            ["office" => "PA-MISD", "service" => "LED WALL OPERATION"],
            ["office" => "PA-MISD", "service" => "Media Scanning"],
            ["office" => "PA-MISD", "service" => "Post Inspection"],
            ["office" => "PA-MISD", "service" => "Pre-Purchase"],
            ["office" => "PA-MISD", "service" => "Preventive Maintenance"],
            ["office" => "PA-MISD", "service" => "Request for Service"],
            ["office" => "PA-MISD", "service" => "Other Services"],
            ["office" => "GO-PISD", "service" => "Administrative Services"],
            ["office" => "GO-PISD", "service" => "Information Management Services"],
            ["office" => "GO-PISD", "service" => "Other Services"],
            ["office" => "PLO", "service" => "Legal Advise"],
            ["office" => "PLO", "service" => "Legal Review"],
            ["office" => "PLO", "service" => "Other Services"],
            ["office" => "PPDO", "service" => "CLUP"],
            ["office" => "PPDO", "service" => "Planning Services"],
            ["office" => "PPDO", "service" => "Provision of Data/ Information/Maps to Clients"],
            ["office" => "PPDO", "service" => "Provision of Technical Services (CSO)"],
            ["office" => "PPDO", "service" => "Review of Program/ Project Design"],
            ["office" => "PPDO", "service" => "Review of Program/ Training/Activity/Project Design"],
            ["office" => "PPDO", "service" => "Other Services"],
            ["office" => "ProVet", "service" => "Administrative Services"],
            ["office" => "ProVet", "service" => "Animal Health Services"],
            ["office" => "ProVet", "service" => "Animal Production Services"],
            ["office" => "ProVet", "service" => "Other Services"],
            ["office" => "PSWDO", "service" => "PSWDO Services"],
            ["office" => "PSWDO", "service" => "Other Services"],
            ["office" => "PTIEDO", "service" => "PTIEDO Services"],
            ["office" => "PTIEDO", "service" => "Other Services"],
            ["office" => "PTIEDO-Tourism", "service" => "Tourism Services"],
            ["office" => "PTIEDO-Tourism", "service" => "Other Services"],
            ["office" => "PTO", "service" => "Admin Services"],
            ["office" => "PTO", "service" => "Cash Disbursement Services"],
            ["office" => "PTO", "service" => "Cert. of Credible Tax"],
            ["office" => "PTO", "service" => "Cert. of Sand and Gravel"],
            ["office" => "PTO", "service" => "Cert. of Transport"],
            ["office" => "PTO", "service" => "Real Property Tax Services"],
            ["office" => "PTO", "service" => "Other Services"],
            ["office" => "GO-SCD", "service" => "Special Concerns' Services"],
            ["office" => "GO-SCD", "service" => "Other Services"],
            ["office" => "SP-OVG", "service" => "Assisting Clients"],
            ["office" => "SP-OVG", "service" => "Other Services"],
            ["office" => "SP-Records", "service" => "Local Legislation/ SP Records"],
            ["office" => "SP-Records", "service" => "Other Services"]
        ];
        foreach ($services as $service) {

            $officeMatch = \App\Models\Office::where('abbr', $service["office"])->first();
            if ($officeMatch) {
                //create service
                \App\Models\Service::create([
                    'office_id' => $officeMatch->id,
                    'name' => $service["service"]
                ]);
            } else {
                dd($service["office"], $service["service"]);
            }
        }

    }
}
