version: '3'
services:
    browserless:
        container_name: "browserless"
        image: browserless/chrome:latest
        environment:
            - MAX_PAYLOAD_SIZE=100mb
            - HOST=browserless
        #ports:
        #    - '${FORWARD_BROWSERLESS_PORT:-3000}:3000'
        networks:
            - sail
        restart: always
    laravel.test:
        container_name: "laravel.test"
        build:
            context: ./docker/runtimes/7.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-7.4/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
            - ~/.composer/docker-cache/:/root/.composer:cached
        networks:
            - sail
        restart: always
        depends_on:
            - mysql
            # - redis
            # - selenium

    # selenium:
    #     image: 'selenium/standalone-chrome'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     networks:
    #         - sail
    #     depends_on:
    #         - laravel.test
    mysql:
        container_name: "mysql"
        image: 'mariadb:10.5.8'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        restart: always
    # redis:
    #     image: 'redis:alpine'
    #     ports:
    #         - '${FORWARD_REDIS_PORT:-6379}:6379'
    #     volumes:
    #         - 'sailredis:/data'
    #     networks:
    #         - sail
    # memcached:
    #     image: 'memcached:alpine'
    #     ports:
    #         - '11211:11211'
    #     networks:
    #         - sail
    # mailhog:
    #     image: 'mailhog/mailhog:latest'
    #     ports:
    #         - 1025:1025
    #         - 8025:8025
    #     networks:
    #         - sail
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
